//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars_s_RFID
    {
        public int id { get; set; }
        public System.DateTime date_record { get; set; }
        public int epc { get; set; }
        public int number_car { get; set; }
        public int status_active { get; set; }
    
        public virtual cars cars { get; set; }
        public virtual RFID_metki RFID_metki { get; set; }
        public virtual status_active status_active1 { get; set; }
    }
}
